#ifndef __GN_TOKENTYPE__
#define __GN_TOKENTYPE__
// This file was automatically generated by EbnfStudio; don't modify it!


#include <QByteArray>

namespace Gn {
	enum TokenType {
		Tok_Invalid = 0,

		TT_Literals,
		Tok_Bang,
		Tok_BangEq,
		Tok_Hash,
		Tok_2Amp,
		Tok_Lpar,
		Tok_Rpar,
		Tok_Plus,
		Tok_PlusEq,
		Tok_Comma,
		Tok_Minus,
		Tok_MinusEq,
		Tok_Dot,
		Tok_Lt,
		Tok_Leq,
		Tok_Eq,
		Tok_2Eq,
		Tok_Gt,
		Tok_Geq,
		Tok_Lbrack,
		Tok_Rbrack,
		Tok_Lbrace,
		Tok_2Bar,
		Tok_Rbrace,

		TT_Keywords,
		Tok_else,
		Tok_false,
		Tok_if,
		Tok_true,

		TT_Specials,
		Tok_identifier,
		Tok_integer,
		Tok_string,
		Tok_Comment,
		Tok_Eof,

		TT_MaxToken,

		TT_Max
	};

	const char* tokenTypeString( int ); // Pretty with punctuation chars
	const char* tokenTypeName( int ); // Just the names without punctuation chars
	bool tokenTypeIsLiteral( int );
	bool tokenTypeIsKeyword( int );
	bool tokenTypeIsSpecial( int );
	TokenType tokenTypeFromString( const QByteArray& str, int* pos = 0 );
}
#endif // __GN_TOKENTYPE__
